### PR TITLE
Update harbour-sailbook-es.ts

### PR DESCRIPTION
**Pull request by ghost**
- Many fixes
 # Can you add this strings to have a FULL translate ! " Pulldown menu "
captura_20170815_001

### CODE REVIEW

**Comment by Caballlero** [comment]
??

**Comment by ghost** [comment]
I send you an email with the new strings. ;)

**Comment by ghost** [comment]
You already confused me. ..

**Comment by ghost** [comment]
You just need to add the lasted 3 strings to your translation file as the example i have send you, and then email me this back as when i do changes you changes will be lost, i have done changes to the code. It's easy... ;)

**Comment by Caballlero** [comment]
Let me know if all it is OK. . ..

**Comment by ghost** [comment]
Ok the code is updated now, so you can make the changes now also. Thanks!

**Comment by ghost** [comment]
OK.
Thank you very much . . .

**Comment by Caballlero** [comment]
: )
Where this norton, the "file manager" I saw it in your github. I was preparing a translation for that app too, but I no longer see it on your github
Thanks . . .

**Comment by ghost** [comment]
No its removed i need to recode the complete app, so in some time i put it here again when it is complete ready. sorry....

**Comment by ghost** [comment]
It  is okay
Once again thank you for Sailbook, very nice app =  )

**Comment by ghost** [comment]
No problem thanks for the translation.
I have now made a Transflex page better for translation.
https://www.transifex.com/sailbook/sailbook/

**Pull request merged**
