### PR TITLE
WiFi/Mobile switcher

### LINKED ISSUE #23: WiFi/Mobile connection detection using DBus
If the user disables the Internet connection or switches between WiFi/Mobile we should be notified directly using DBus. Polling the ConnMan network state files is too slow, resource hungry and ugly.

### PR DESCRIPTION
**Pull request by DylanVanAssche**
WiFi/Mobile switcher automatically reconnects when back on online using DBus.
For easy implementation this is done in QML in order to access directly the Webview.
Fixed #23

### CODE REVIEW

**Review by codeandcreate — CHANGES_REQUESTED** [review]
Hey, looks good, but please remove / comment out the line 55 in qml/harbour-sailbook.qml

**Comment by DylanVanAssche** [comment]
@codeandcreate Oh yeah thanks! Will do that :)

**Comment by DylanVanAssche** [comment]
@codeandcreate better? ^^

**Review by codeandcreate — APPROVED** [review]

**Comment by codeandcreate** [comment]
yeah ;)

**Pull request merged**
