### PR TITLE
Update harbour-sailbook.hu file

### PR DESCRIPTION
**Pull request by 1Zgp**
Hi, I am the same person who translated this on transifex. i have seen a lot of mistakes i made,but i have no reviewer rights there, so i cannot make changes in that file. that's why i am asking this update. Thanks!

### CODE REVIEW

**Comment by ghost** [comment]
Hi,
Best way you can do this via Transiflex then we can update it automatic.
Thanks

**Comment by 1Zgp** [comment]
Yes, it would be the best way, but someone reviewed all translations (however i am the single member of hungarian team), and i can't make any changes, i can only suggest. May i ask you to add me as a reviewer on transifex then (I use another nick on trfex)? Thanks in advance!

**Comment by ghost** [comment]
Hi, yes i will fix it

**Comment by 1Zgp** [comment]
Hi,
Thanks again, i made it on trfex. Should i close this pull request, shouldn't i?

**Comment by ghost** [comment]
No on the next release we will update the language. thanks

**Pull request closed without merging**
